// ------------ Problem 5 ------------
// ------- Ticket Change  --------
// 
// A movie in this theatre costs $25, and every person in line has a single
// $25, $50, or $100 bill. The cashier has $0 in change.
// 
// If the cashier must sell tickets in the order of the line, will he be able 
// to sell a ticket to every person in the line and provide them change?


// tickets
// Input: An array containing only the numbers 25,50,and 100
// Output: "YES" if there is enough change generated by the people, "NO" otherwise
// Notes: 

var tickets = function(peopleInLine) {
  return 0;
}


// test cases
console.log(tickets([25,25,25,25,25]) + ' should equal "YES"');
console.log(tickets([25,25,50,25,25,100]) + ' should equal "YES"');
console.log(tickets([25,50,100]) + ' should equal "NO"');
console.log(tickets([]) + ' should equal "YES"');
console.log(tickets([25,50,25,100,25,25]) + ' should equal "YES"');