// ------------ Problem 2 ------------
// ----- Even Fibonacci numbers ------
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence 
// whose values do not exceed four million, 
// find the sum of the even-valued terms.


// evenFibonacciSum
// Input: An integer N
// Output: Sum of all even fibonacci numbers not larger than N

var evenFibonacciSum = function(n) {
  return 0;
}


// test cases
console.log(evenFibonacciSum(10) + ' should equal 8');
console.log(evenFibonacciSum(0) + ' should equal 0');
console.log(evenFibonacciSum(100) + ' should equal 44');
console.log(evenFibonacciSum(5) + ' should equal 2');

console.log('Result for evenFibonacciSum(4000000): ' + evenFibonacciSum(4000000));
